# Perceptron from scratch

In this assignment, we will be reimplementing a Neural Networks from scratch.

In part A, we are going to build a simple Perceptron on a small dataset that contains only 3 features.

<img src='https://drive.google.com/uc?id=1aUtXFBMKUumwfZ-2jmR5SIvNYPaD-t2x' width="500" height="250">

Some of the code have already been defined for you. You need only to add your code in the sections specified (marked with **TODO**). Some assert statements have been added to verify the expected outputs are correct. If it does throw an error, this means your implementation is behaving as expected.

Note: You are only allowed to use Numpy and Pandas packages for the implemention of Perceptron. You can not packages such as Sklearn or Tensorflow.

# 1. Import Required Packages

[1.1] We are going to use numpy and random packages

In [1]:
import numpy as np
import random

# 2. Define Dataset

[2.1] We are going to use a simple dataset containing 3 features and 7 observations. The target variable is a binary outcome (either 0 or 1)

In [2]:
input_set = np.array([[0,1,0], [0,0,1], [1,0,0], [1,1,0], [1,1,1], [0,1,1], [0,1,0]])
labels = np.array([[1], [0], [0], [1], [1], [0], [1]])

# 3. Set Initial Parameters

[3.1] Let's set the seed in order to have reproducible outcomes

In [3]:
np.random.seed(42)

[3.2] **TODO**: Define a function that will create a Numpy array of a given shape with random values.


For example, `initialise_array(3,1)` will return an array of dimensions (3,1)that can look like this (values may be different):


`array([[0.37454012],
       [0.95071431],
       [0.73199394]])`

In [4]:
# TODO (Students need to fill this section)

import numpy as np

def initialise_array(shape):
    """
    Create a Numpy array with random values of a specified shape.

    Parameters:
    - shape: tuple, the shape of the array to create. For example, (rows, cols).

    Returns:
    - Numpy array of the specified shape with random values.
    """
    # Correctly indented block
    return np.random.rand(*shape)

# Example usage:
array = initialise_array((3, 1))
print(array)


[[0.37454012]
 [0.95071431]
 [0.73199394]]


[3.3] **TODO**: Create a Numpy array of shape (3,1) called `init_weights` filled with random values using `initialise_array()` and print them.

In [5]:
# TODO (Students need to fill this section)
init_weights = initialise_array((3, 1))
print(init_weights)

[[0.59865848]
 [0.15601864]
 [0.15599452]]


[3.4] **TODO**: Create a Numpy array of shape (1,) called `init_bias` filled with a random value using `initialise_array()` and print it.

In [6]:
# TODO (Students need to fill this section)
init_bias =initialise_array((1,))
print(init_bias)

[0.05808361]


[3.5] Assert statements to check your created variables have the expected shapes

In [7]:
assert init_weights.shape == (3, 1)
assert init_bias.shape == (1,)

# 4. Define Linear Function
In this section we are going to implement the linear function of a neuron:

<img src='https://drive.google.com/uc?id=1vhfpGffqletFDzMIvWkCMR2jrHE5MBy5' width="500" height="300">

[4.1] **TODO**: Define a function that will perform a dot product on the provided X and weights and add the bias to it

In [8]:
# TODO (Students need to fill this section)
def linear(X, weights, bias):
    """
    Implement the linear function of a neuron.

    This function computes the dot product of input data X and weights, then adds the bias.

    Parameters:
    - X: Numpy array of shape (m, n), where m is the number of examples and n is the number of features.
    - weights: Numpy array of shape (n, 1), where n is the number of features.
    - bias: Scalar or Numpy array of shape (1,) representing the bias term.

    Returns:
    - A Numpy array of shape (m, 1) representing the linear transformation of the input data.
    """
    dot_product = np.dot(X, weights)  # Make sure this line is properly indented
    output = dot_product + bias       # This line as well
    return output

[4.2] Assert statements to check your linear function is behaving as expected

In [9]:
test_weights = [[0.37454012],[0.95071431],[0.73199394]]
test_bias = [0.59865848]
assert linear(X=input_set[0], weights=test_weights, bias=test_bias)[0] == 1.54937279
assert linear(X=input_set[1], weights=test_weights, bias=test_bias)[0] == 1.3306524199999998
assert linear(X=input_set[2], weights=test_weights, bias=test_bias)[0] == 0.9731985999999999
assert linear(X=input_set[3], weights=test_weights, bias=test_bias)[0] == 1.9239129099999999
assert linear(X=input_set[4], weights=test_weights, bias=test_bias)[0] == 2.65590685
assert linear(X=input_set[5], weights=test_weights, bias=test_bias)[0] == 2.28136673
assert linear(X=input_set[6], weights=test_weights, bias=test_bias)[0] == 1.54937279

# 5. Activation Function

In the forward pass, an activation function is applied on the result of the linear function. We are going to implement the sigmoid function and its derivative:

<img src='https://drive.google.com/uc?id=1LK7yjCp4KBICYNvTXzILQUzQbkm7G9xC' width="200" height="100">
<img src='https://drive.google.com/uc?id=1f5jUyw0wgiVufNqveeJVZnQc6pOrDJXD' width="300" height="100">


[5.1] **TODO**: Define a function that will implement the sigmoid function

In [10]:
# TODO (Students need to fill this section)
def sigmoid(x):
    """
    Compute the sigmoid of x.

    Parameters:
    - x: A scalar or Numpy array of any size.

    Returns:
    - The sigmoid of x, applied element-wise if x is an array.
    """
    return 1 / (1 + np.exp(-x))

# Test the sigmoid function with a simple array
test_array = np.array([-1, 0, 1])
sigmoid(test_array)

array([0.26894142, 0.5       , 0.73105858])

[5.2] Assert statements to check your sigmoid function is behaving as expected

In [11]:
assert sigmoid(0) == 0.5
assert sigmoid(1) == 0.7310585786300049
assert sigmoid(-1) == 0.2689414213699951
assert sigmoid(9999999999999) == 1.0
assert sigmoid(-9999999999999) == 0.0

C:\Users\nipan\AppData\Local\Temp\ipykernel_14048\2326164803.py:12: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


[5.3] **TODO**: Define a function that will implement the derivative of the sigmoid function

In [12]:
# TODO (Students need to fill this section)
def sigmoid_derivative(x):
    """
    Compute the derivative of the sigmoid function.

    Parameters:
    - x: A scalar or Numpy array of any size.

    Returns:
    - The derivative of the sigmoid function, applied element-wise if x is an array.
    """
    # First, compute the sigmoid of x
    sigmoid_x = 1 / (1 + np.exp(-x))
    # Then, calculate and return the derivative of the sigmoid function
    return sigmoid_x * (1 - sigmoid_x)

# Example usage
x = np.array([-1, 0, 1])
print(sigmoid_derivative(x))

[0.19661193 0.25       0.19661193]


[5.2] Assert statements to check your sigmoid_derivative function is behaving as expected

In [13]:
assert sigmoid_derivative(0) == 0.25
assert sigmoid_derivative(1) == 0.19661193324148185
assert sigmoid_derivative(-1) == 0.19661193324148185
assert sigmoid_derivative(9999999999999) == 0.0
assert sigmoid_derivative(-9999999999999) == 0.0

C:\Users\nipan\AppData\Local\Temp\ipykernel_14048\3695536295.py:13: RuntimeWarning: overflow encountered in exp
  sigmoid_x = 1 / (1 + np.exp(-x))


# 6. Forward Pass

Now we have everything we need to implement the forward propagation

[6.1] **TODO**: Define a function that will implement the forward pass (apply linear function on the input followed by the sigmoid activation function)

In [14]:
# TODO (Students need to fill this section)
def forward(X, weights, bias):
    """
    Perform the forward pass by applying a linear function and then the sigmoid activation.

    Parameters:
    - X: Numpy array of input data.
    - weights: Numpy array of weights.
    - bias: Scalar or Numpy array of bias.

    Returns:
    - The output of the neural network at this layer, after applying the sigmoid activation.
    """
    # Apply linear function
    linear_result = np.dot(X, weights) + bias

    # Apply sigmoid activation
    sigmoid_result = 1 / (1 + np.exp(-linear_result))

    return sigmoid_result

[6.2] Assert statements to check your forward function is behaving as expected

In [15]:
assert forward(X=input_set[0], weights=test_weights, bias=test_bias)[0] == 0.8248231247647452
assert forward(X=input_set[1], weights=test_weights, bias=test_bias)[0] == 0.7909485322272701
assert forward(X=input_set[2], weights=test_weights, bias=test_bias)[0] == 0.7257565873271445
assert forward(X=input_set[3], weights=test_weights, bias=test_bias)[0] == 0.8725741389540382
assert forward(X=input_set[4], weights=test_weights, bias=test_bias)[0] == 0.9343741240208852
assert forward(X=input_set[5], weights=test_weights, bias=test_bias)[0] == 0.9073220375080315
assert forward(X=input_set[6], weights=test_weights, bias=test_bias)[0] == 0.8248231247647452

# 7. Calculate Error

After the forward pass, the Neural Networks will calculate the error between its predictions (output of forward pass) and the actual targets.

[7.1] **TODO**: Define a function that will implement the error calculation (difference between predictions and actual targets)

In [16]:
# TODO (Students need to fill this section)
import numpy as np

def calculate_error(actual, pred):
    """
    Calculate the total error between actual targets and predictions.

    Parameters:
    actual (array-like): Array of actual target values
    pred (array-like): Array of predicted values

    Returns:
    float: Total error (sum of differences between predictions and actual targets)
    """
    return np.sum(pred - actual)



[7.2] Assert statements to check your calculate_error function is behaving as expected

In [17]:
test_actual = np.array([0,0,0,1,1,1])
assert calculate_error(actual=test_actual, pred=[0,0,0,1,1,1]).sum() == 0
assert calculate_error(actual=test_actual, pred=[0,0,0,1,1,0]).sum() == -1
assert calculate_error(actual=test_actual, pred=[0,0,0,0,0,0]).sum() == -3

# 8. Calculate Gradients
Once the error has been calculated, a Neural Networks will use this information to update its weights accordingly.

[8.1] Let's creata function that calculate the gradients using the sigmoid derivative function and applying the chain rule.

In [18]:
def calculate_gradients(pred, error, input):
  dpred = sigmoid_derivative(pred)
  z_del = error * dpred
  gradients = np.dot(input.T, z_del)
  return gradients, z_del

# 9. Training

Now that we built all the components of a Neural Networks, we can finally train it on our dataset.

[9.1] Create 2 variables called `weights` and `bias` that will respectively take the value of `init_weights` and `init_bias`

In [19]:
weights = init_weights
bias = init_bias

[9.2] Create a variable called `lr` that will be used as the learning rate for updating the weights

In [20]:
lr = 0.5

[9.3] Create a variable called `epochs` with the value 10000. This will the number of times the Neural Networks will process the entire dataset and update its weights

In [21]:
epochs = 10000

[9.4] Create a for loop that will perform the training of our Neural Networks

In [22]:
for epoch in range(epochs):
    inputs = input_set

    # Forward Propagation
    z = forward(X=inputs, weights=weights, bias=bias)

    # Error
    error = calculate_error(actual=labels, pred=z)

    # Back Propagation
    gradients, z_del = calculate_gradients(pred=z, error=error, input=input_set)

    # Update parameters
    weights = weights - lr * gradients
    for num in z_del:
        bias = bias - lr * num


[9.5] **TODO** Print the final values of `weights` and `bias`

In [23]:
# TODO (Students need to fill this section)
print("Final Weights:", weights)
print("Final Bias:", bias)


Final Weights: [[ 0.99021769]
 [ 2.19115559]
 [-0.27866997]]
Final Bias: [-1.57419278]


# 10. Compare before and after training

Let's compare the predictions of our Neural Networks before (using `init_weights` and `init_bias`) and after the training (using `weights` and `bias`)

[10.1] Create a function to display the values of a single observation from the dataset (using its index), the error and the actual target and prediction

In [24]:
def compare_pred(weights, bias, index, X, y):
    pred = forward(X=X[index], weights=weights, bias=bias)
    actual = y[index]
    error = calculate_error(actual, pred)
    print(f"{X[index]} - Error {error} - Actual: {actual} - Pred: {pred}")

[10.2] Compare the results on the first observation (index 0)

In [25]:
compare_pred(weights=init_weights, bias=init_bias, index=0, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=0, X=input_set, y=labels)

[0 1 0] - Error -0.44667797055005865 - Actual: [1] - Pred: [0.55332203]
[0 1 0] - Error -0.3504725285117549 - Actual: [1] - Pred: [0.64952747]


[10.3] Compare the results on the second observation (index 1)

In [26]:
compare_pred(weights=init_weights, bias=init_bias, index=1, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=1, X=input_set, y=labels)

[0 0 1] - Error 0.5533160679949385 - Actual: [0] - Pred: [0.55331607]
[0 0 1] - Error 0.13553712744025928 - Actual: [0] - Pred: [0.13553713]


[10.4] Compare the results on the third observation (index 2)

In [27]:
compare_pred(weights=init_weights, bias=init_bias, index=2, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=2, X=input_set, y=labels)

[1 0 0] - Error 0.6585281663218256 - Actual: [0] - Pred: [0.65852817]
[1 0 0] - Error 0.3580184391313131 - Actual: [0] - Pred: [0.35801844]


[10.5] Compare the results on the forth observation (index 3)

In [28]:
compare_pred(weights=init_weights, bias=init_bias, index=3, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=3, X=input_set, y=labels)

[1 1 0] - Error -0.30730251163799815 - Actual: [1] - Pred: [0.69269749]
[1 1 0] - Error -0.16698043290039477 - Actual: [1] - Pred: [0.83301957]


[10.6] Compare the results on the fifth observation (index 4)

In [29]:
compare_pred(weights=init_weights, bias=init_bias, index=4, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=4, X=input_set, y=labels)

[1 1 1] - Error -0.27512867537455343 - Actual: [1] - Pred: [0.72487132]
[1 1 1] - Error -0.20940584902461346 - Actual: [1] - Pred: [0.79059415]


[10.7] Compare the results on the sixth observation (index 5)

In [30]:
compare_pred(weights=init_weights, bias=init_bias, index=5, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=5, X=input_set, y=labels)

[0 1 1] - Error 0.5914823619815118 - Actual: [0] - Pred: [0.59148236]
[0 1 1] - Error 0.5837757723770773 - Actual: [0] - Pred: [0.58377577]


[10.8] Compare the results on the sixth observation (index 5)

In [31]:
compare_pred(weights=init_weights, bias=init_bias, index=6, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=6, X=input_set, y=labels)

[0 1 0] - Error -0.44667797055005865 - Actual: [1] - Pred: [0.55332203]
[0 1 0] - Error -0.3504725285117549 - Actual: [1] - Pred: [0.64952747]


We can see after 10000 epochs, our Neural Networks is performing extremely well on our dataset. It has found pretty good values for the weights and bias to make accurate prediction.

Please submit this notebook into Canvas. Name it following this rule: *assignment1-partA-\<student_id\>.ipynb*